version: "3.8"
services:
    redis:
        build: .
        env_file: .env
        volumes:
            - redis-data.rdb:/var/lib/redis/redis.rdb
            - redis.log:/var/log/redis/redis-server.log

        command: redis-server /etc/redis/redis.conf --requirepass $REDIS_PASSWORD 
        ports:
            - $REDIS_PORT:6379
      
volumes:
    redis-data.rdb:
        external: false
    redis.log:
        external: false
