version: "3.2"
services:

 redis:
    env_file: .env
    image: "redis:alpine"
    restart: always

    volumes:
     - ./redis-data:/var/lib/redis
     - ./redis.conf:/usr/local/etc/redis/redis.conf
     - ./redis.log:/usr/local/etc/redis/redis.log

    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6370:6379"
