version: "3.8"
services:
    redis-standalone:
        build: .
        env_file: .env
        volumes:
            - redisvol:/data

        command: redis-server /usr/local/etc/redis/redis.conf --requirepass $REDIS_PASSWORD 
        ports:
            - $REDIS_PORT:6379
      
      
      
volumes:
    redisvol:
        driver: local
        driver_opts:
            o: bind
            type: none 
            device: ./data
